= CF Workshop Continuous Delivery Lab

== Intro

This lab will guide you through building a *BASIC* continuous delivery pipeline using Jenkins and Cloud Foundry.

== Initial Setup

. Fork the Spring-Music repository. If you do not have a github account, you can use this repo

https://github.com/cloudfoundry-samples/spring-music.git

. Edit the manifest.yml at the root of the forked spring-music repository. Change the *host* from ${random-word} to your initials. Jenkins does not like the special characters in the host field and will give an error.
  
. Login to your Jenkins instance at https://jenkins-0.system.pivotalpoc.hosts.disney.pvt with MyID link


== Create the Build Job

. Click *New Item*, give it the name *spring-music* and select ``Build a free-style software project.'' Then click +OK+.

== Configure Git

. Under *Source Code Management*, select *Git*, and supply your repository URL (e.g. `https://github.com/<YOUR_GIT_USERNAME>/spring-music`). Leave credentials as *none*.
. If you weren't able to fork Spring-Music, just use https://github.com/cloudfoundry-samples/spring-music

== Configure Gradle Build

. Select *Add Build Step* and then *Invoke Gradle Script*.

. Select *Use Grade Wrapper*.

. Check both *Make gradlew executable* and *From Root Build Script Directory*.

. In switches, enter `-Pbuildversion=$BUILD_NUMBER`.

. In tasks, enter `clean assemble`.

. In build file, enter `build.gradle`.

. Check *Force GRADLE_USER_HOME to use workspace.

. On "Build Triggers", select "Build when a change is pushed to GitHub"

== Execute Shell
[source,bash]
----
DEPLOYED_VERSION_CMD=$(CF_COLOR=false cf apps | grep 'mapUS.' | cut -d" " -f1)
export BUILD_VERSION="1.2"
export DEPLOYED_VERSION_CMD
echo DEPLOYED_VERSION_CMD
export ROUTE_VERSION="default"
echo "Deployed Version: $DEPLOYED_VERSION"
echo "Route Version: $ROUTE_VERSION"

# Save your api target in variable API
export API=https://api.system.pivotalpoc.hosts.disney.pvt 

# Set current target api to API
cf api --skip-ssl-validation $API

# Use the jenkins_sercice credentials here to login to your org and space
cf login -u jenkins_service -p cl0udc0w -o YourOrg -s YourSpace

# Create an instance of the mysql service
cf create-service p-mysql 100mb spring-music-db

# Create/Update the spring-music app using the versioned manifest.yml, but dont start
cf push spring-music -n spring-music-dtss -f manifest.yml --no-start

# Bind the application to the service instance
cf bind-service spring-music spring-music-db

# Start the application
cf start spring-music

----


== Execute Build Job

. Select *Build Now*.

. Select the build in *Build History*, then select *Console Output*.

. Jenkins should build and push the app, then you can click the link at the bottom to see the running app.


